#!/bin/bash

lighthouse --config-path=./custom-config.js $1 --preset="perf" --quiet --chrome-flags="--headless"  --disable-device-emulation --output json --output-path=./lighthouse-results-$(date +%s).json
